### PR TITLE
Provide different icon sizes in mobile context

### PR DESCRIPTION
**Pull request by ddellacosta**
https://www.pivotaltracker.com/story/show/161238882

@tadler asking for your review on this one since I'm not sure if I'm doing this the best possible way--let me know if you see a more effective approach here.

### CODE REVIEW

**Comment by tadler** [comment]
So I'm not super sure about how this code works -- the only thing that stands out to me is the dimensions of each icon. It would be great if we could define only one dimension and let the other set itself relative to that. Possible?

**Comment by ddellacosta** [comment]
@tadler I'm not sure I follow entirely--can you explain further?

**Comment by tadler** [comment]
@ddellacosta so if these were being sized in CSS, you'd be able to say something like `width: 40px` and trust that the height would scale accordingly, and the image would maintain its proportions. I'm wondering if this would work the same way.

**Comment by tadler** [comment]
@ddellacosta Gonna approve this because it's not actually a big deal, just thinking it'd be nice since it'd be less magic-numbery.

**Comment by ddellacosta** [comment]
I'm going to go ahead and push this to staging as I'm not sure the CSS-based solution will be simple enough at this point without rethinking a bunch of other stuff--will keep it in mind for a later refactoring though.

**Pull request merged**
