### PR TITLE
Misc ui cleanup 2

### PR DESCRIPTION
**Pull request by tank157**
[Pivotal Card](https://www.pivotaltracker.com/story/show/157946436)
[Pivotal Card](https://www.pivotaltracker.com/story/show/157945621)

### CODE REVIEW

**Comment by tank157** [comment]
screenshot_379

**Comment by tank157** [comment]
screenshot_380

**Comment by tank157** [comment]
screenshot_381

**Comment by tank157** [comment]
screenshot_382

**Comment by tank157** [comment]
That's some good detail to check on. I just ran this and collapsed down all the expandable cards and the background stayed a solid background color the whole way to the bottom, even when there was a bunch of extra space, so i think this is good.

**Comment by ddellacosta** [comment]
@tank157 Excellent! Thanks for confirming.

**Comment by tank157** [comment]
It should be getting deployed shortly, so hopefully we can confirm on staging too.

**Pull request merged**
