### PR TITLE
Header elements

### PR DESCRIPTION
**Pull request by lizstarin**
after some `git` drama...
I'm not sure where to locate any `h1`s, although I saw at least one in the code. It seems we should have one on the page though.

### CODE REVIEW

**Comment by lizstarin** [comment]
Oohh, good catch on the styling. I did make some CSS changes to keep the styling the same, but looks like I missed a couple spots.

**Comment by tank157** [comment]
Yeah, it's close, but a few things drifted. But like I said, aside from the maybe too much space around a location name in the locations cards, I like the other slight differences more anyway. But I suppose styling questions are best handled by someone else with an actual sense of style :)

**Comment by lizstarin** [comment]
Did you catch anything other than the font size in the tabs?

**Comment by tank157** [comment]
The location name is now bolded where it wasn't before (and the aforementioned extra padding around it), but I think the bolding itself looks good. And yeah, the tab names got smaller and I think that's good too.

And now that I take a closer look, on the Ballot tab, the card title is now offset from the line level of the carrot/upside down carrot marker that indicates if the card is open or closed. It's pretty subtle, but it's definitely shifted up higher by about half a line height or so. It becomes more obvious if you narrow down the window so they get closer to each other.

See the screenshots below, where I added a purple line to illustrate the difference.

before
screenshot_607

after
screenshot_606

**Pull request merged**
